tokenizer:
  model_name: t5-base
  padding_side: right
  truncation_side: right
  pad_token_as_eos_token: False
  max_length: 1024

datapool:
  id: casino
  args:
    processed_data_dir: "/project/glucas_540/kchawla/nego_control_f22/base_model/data/casino/"

alg:
  id: supervised
  training_args:
    per_device_train_batch_size: 16
    num_train_epochs: 15
    weight_decay: 0.01
    learning_rate: 0.00002
    save_total_limit: 3
    evaluation_strategy: epoch
    logging_strategy: epoch
    save_strategy: epoch
  model_type: seq2seq
  model_name: t5-base
  generation_kwargs:
    do_sample: True
    top_k: 50
    top_p: 0.6
    min_length: 5
    num_beams: 1
    max_new_tokens: 192
    no_repeat_ngram_size: 3
    post_processing_fn: null

train_evaluation:
  eval_batch_size: 50
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: sacre_bleu
      args:
        tokenize: "intl"

